apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crypto
  name: virt-launcher-crypto
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crypto
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crypto
    spec:
      containers:
      - image: registry.access.redhat.com/ubi9/ubi
        imagePullPolicy: Always
        name: ubi
        command: ["sleep"]
        args: ["inf"]
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
