apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubevirt.io/domain: crypto
    sha1.kubevirt.io/enabled: "true"
  labels:
    app: crypto
  name: virt-launcher-crypto
spec:
  containers:
  - image: registry.redhat.io/container-native-virtualization/virt-launcher-rhel9:v4.13
    imagePullPolicy: Always
    name: compute
    command: ["sh"]
    args: ["-c", "update-crypto-policies --show ; ls -shal /etc/.sha1_try_enable ; sleep inf"]
  securityContext: {}
  terminationGracePeriodSeconds: 1
status: {}
