apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubevirt.io/domain: crypto
  labels:
    app: crypto
  name: virt-launcher-crypto
spec:
  containers:
  - image: registry.redhat.io/container-native-virtualization/virt-launcher-rhel9:v4.13
    imagePullPolicy: Always
    name: compute
    command: ["bash"]
    args: ["-c", "env | grep OPENSSL ; sleep inf"]
  securityContext: {}
  terminationGracePeriodSeconds: 1
status: {}
